### ISSUE TITLE
Typos In April-May Summary

### ISSUE THREAD

**Issue by ghost** [BitShares-Committee/BitShares-Committee.github.io#3]
https://committee.bitshares.works/2018/05/08/april-may-summary/

Typo "As `fas` as the market operations budget is concerned, the accounting is as follows:"

Typo "In other news, the first Graphene DevCon was `succesfully` concluded in Shanghai over the last weekend. Committee member jademont has published a relevant article."

**Comment by clockworkgr** [comment]
Fixed https://github.com/BitShares-Committee/BitShares-Committee.github.io/commit/8ff6cbfbbccac628322977c305eb3044853fdad3

Cheers
